/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Unicordoba.Registro_Control.Interfaz_Secundaria.BasicaDos;

import Unicordoba.Registro_Control.Interfaz_Principal.FramePrincipal;

/**
 *
 * @author AndresFelipe
 */
public class VentanaIniciarSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaIniciarSesion
     */
    public VentanaIniciarSesion() {
        initComponents();
        EstadoInicial();
        
    }

    private void EstadoInicial(){
        TFieldCodigo.setText(LCodigoHuella.getText());
        TFieldCodigo.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPanelLogin = new javax.swing.JTabbedPane();
        PanelIniciarSesion = new javax.swing.JPanel();
        TFieldCodigo = new javax.swing.JTextField();
        LCodigoHuella = new javax.swing.JLabel();
        BotonAcceder = new javax.swing.JButton();
        LClave = new javax.swing.JLabel();
        TFieldClaveAcceso = new javax.swing.JTextField();
        LCodigo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        TFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LCodigoHuella.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LCodigoHuella.setText("1010101010");
        LCodigoHuella.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        BotonAcceder.setText("Acceder");
        BotonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccederActionPerformed(evt);
            }
        });

        LClave.setText("Clave:");

        LCodigo.setText("Codigo:");

        javax.swing.GroupLayout PanelIniciarSesionLayout = new javax.swing.GroupLayout(PanelIniciarSesion);
        PanelIniciarSesion.setLayout(PanelIniciarSesionLayout);
        PanelIniciarSesionLayout.setHorizontalGroup(
            PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LCodigoHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFieldCodigo)
                    .addComponent(BotonAcceder, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(TFieldClaveAcceso)
                    .addComponent(LCodigo)
                    .addComponent(LClave))
                .addContainerGap())
        );
        PanelIniciarSesionLayout.setVerticalGroup(
            PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LCodigoHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelIniciarSesionLayout.createSequentialGroup()
                        .addComponent(LCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFieldClaveAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAcceder)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        TabPanelLogin.addTab("Iniciar sesion", PanelIniciarSesion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanelLogin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanelLogin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccederActionPerformed

    }//GEN-LAST:event_BotonAccederActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcceder;
    private javax.swing.JLabel LClave;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LCodigoHuella;
    private javax.swing.JPanel PanelIniciarSesion;
    private javax.swing.JTextField TFieldClaveAcceso;
    private javax.swing.JTextField TFieldCodigo;
    private javax.swing.JTabbedPane TabPanelLogin;
    // End of variables declaration//GEN-END:variables
}
