/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Unicordoba.Registro_Control.Interfaz_Secundaria.Estudiantes;

import Unicordoba.Registro_Control.Base_de_Datos.Controlador.EstudianteJpaController;
import Unicordoba.Registro_Control.Base_de_Datos.Controlador.InformacionBasicaJpaController;
import Unicordoba.Registro_Control.Base_de_Datos.Controlador.InformacionDeSeguridadJpaController;
import Unicordoba.Registro_Control.Base_de_Datos.Controlador.SedeJpaController;
import Unicordoba.Registro_Control.Base_de_Datos.Controlador.exceptions.IllegalOrphanException;
import Unicordoba.Registro_Control.Base_de_Datos.Controlador.exceptions.NonexistentEntityException;
import Unicordoba.Registro_Control.Base_de_Datos.Entity.Estudiante;
import Unicordoba.Registro_Control.Base_de_Datos.Entity.InformacionBasica;
import Unicordoba.Registro_Control.Base_de_Datos.Entity.InformacionDeSeguridad;
import Unicordoba.Registro_Control.Base_de_Datos.Entity.Sede;
import Unicordoba.Registro_Control.Interfaz_Secundaria.BasicaUno.Estado_Ventana;
import Unicordoba.Registro_Control.Interfaz_Secundaria.BasicaUno.IPanelEdicion;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Hp
 */
public class PEstudiantes extends javax.swing.JPanel implements IPanelEdicion{

    /**
     * Creates new form PEstudiantes
     */
    public PEstudiantes() {
        initComponents();
        CargarSede();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cSedes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tIdentificacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tCondigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tCorreo = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lCH = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tClave = new javax.swing.JTextField();
        cEstado = new javax.swing.JComboBox();

        jLabel1.setText("SEDE");

        jLabel2.setText("ID ESTUDIANTE");

        lId.setBackground(new java.awt.Color(255, 255, 255));
        lId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lId.setOpaque(true);

        jLabel4.setText("NOMBRES");

        jLabel5.setText("APELLIDOS");

        jLabel6.setText("TIC / CC");

        jLabel7.setText("CÓDIGO");

        jLabel8.setText("E-MAIL");

        jLabel9.setText("TELEFONO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("T"));

        jButton1.setText("Capturar");

        lCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCH.setText("01010100111");
        lCH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel11.setText("CALVE DE ACCESO");

        jLabel12.setText("ESTADO");

        cEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tIdentificacion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCondigo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTelefono))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tApellidos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNombres))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cSedes, 0, 111, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tClave)
                    .addComponent(cEstado, 0, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(cSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(tIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tCondigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cEstado;
    private javax.swing.JComboBox cSedes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCH;
    private javax.swing.JLabel lId;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tClave;
    private javax.swing.JTextField tCondigo;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tIdentificacion;
    private javax.swing.JTextField tNombres;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables

    private EntityManagerFactory factory;
    private InformacionBasica informacionBasica = null;
    private InformacionDeSeguridad informacionDeSeguridad = null;
    private Estudiante estudiante = null;
    @Override
    public void Guardar(Estado_Ventana estado_Ventana) {
        try {
      
        factory = Persistence.createEntityManagerFactory("R-C_Unicor_LoricaPU");
      
         informacionBasica.setNombres(tNombres.getText());
         informacionBasica.setApellidos(tApellidos.getText());
         informacionBasica.setCodigo(tCondigo.getText());
         informacionBasica.setCorreo(tCorreo.getText());
         informacionBasica.setTelefono(tTelefono.getText());
         informacionBasica.setTiCc(Integer.valueOf(tIdentificacion.getText()));
      
        InformacionBasicaJpaController informacionBasicaJpaController = new InformacionBasicaJpaController(factory);
         
        if (estado_Ventana.equals(Estado_Ventana.NUEVO)) {
                informacionBasicaJpaController.create(informacionBasica);
            } else {
                informacionBasicaJpaController.edit(informacionBasica);
            }
        
        
        informacionDeSeguridad.setClave(tClave.getText());
        informacionDeSeguridad.setCodigoHuella(lCH.getText());
        informacionDeSeguridad.setEstado(cEstado.getSelectedItem().toString());
        
        InformacionDeSeguridadJpaController informacionDeSeguridadJpaController = new InformacionDeSeguridadJpaController(factory);
        
        if (estado_Ventana.equals(Estado_Ventana.NUEVO)) {
                informacionDeSeguridadJpaController.create(informacionDeSeguridad);
            } else {
                informacionDeSeguridadJpaController.edit(informacionDeSeguridad);
            }
        
            estudiante.setInformacionBasicaId(informacionBasica);
            estudiante.setInformacionDeSeguridadidI(informacionDeSeguridad);
            estudiante.setSedeid((Sede) cSedes.getSelectedItem());
            EstudianteJpaController controller = new EstudianteJpaController(factory);
         
        if (estado_Ventana.equals(Estado_Ventana.NUEVO)) {
                controller.create(estudiante);
            } else {
                controller.edit(estudiante);
            }

        } catch (Exception ex) {

            ex.printStackTrace();
        }
        
    }

    @Override
    public void Eliminar() {
        
     try {
            factory = Persistence.createEntityManagerFactory("R-C_Unicor_LoricaPU");

            EstudianteJpaController controller = new EstudianteJpaController(factory);
            controller.destroy(estudiante.getIdEstudiante());
            
            InformacionBasicaJpaController basicaJpaController = new InformacionBasicaJpaController(factory);
            basicaJpaController.destroy(estudiante.getInformacionBasicaId().getId());

            InformacionDeSeguridadJpaController deSeguridadJpaController = new InformacionDeSeguridadJpaController(factory);
            deSeguridadJpaController.destroy(estudiante.getInformacionDeSeguridadidI().getIdI());

        } catch (NonexistentEntityException ex) {
            ex.printStackTrace();
        } catch (IllegalOrphanException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void ActivarEdicion() {
    
    
    }

    @Override
    public void Nuevo() {
        informacionBasica = new InformacionBasica();
        informacionDeSeguridad = new InformacionDeSeguridad();
        estudiante = new Estudiante();
    }

    @Override
    public void Seleccionar(Vector vectorSeleccion) {
     factory = Persistence.createEntityManagerFactory("R-C_Unicor_LoricaPU");
        EstudianteJpaController controller = new EstudianteJpaController(factory);

        this.estudiante = controller.findEstudiante(Integer.valueOf(vectorSeleccion.get(0).toString()));
        this.informacionBasica = estudiante.getInformacionBasicaId();
        this.informacionDeSeguridad = estudiante.getInformacionDeSeguridadidI();

        lId.setText(estudiante.getIdEstudiante().toString());
        tNombres.setText(estudiante.getInformacionBasicaId().getNombres());
        tApellidos.setText(estudiante.getInformacionBasicaId().getApellidos());
        tCondigo.setText(estudiante.getInformacionBasicaId().getCodigo());
        tCorreo.setText(estudiante.getInformacionBasicaId().getCorreo());
        tIdentificacion.setText(estudiante.getInformacionBasicaId().getTiCc() + "");
        tTelefono.setText(estudiante.getInformacionBasicaId().getTelefono() + "");

        lCH.setText(estudiante.getInformacionDeSeguridadidI().getCodigoHuella());
        tClave.setText(estudiante.getInformacionDeSeguridadidI().getClave());
        cEstado.setSelectedItem(estudiante.getInformacionDeSeguridadidI().getEstado());

        cSedes.setSelectedItem(estudiante.getSedeid());
    
    }

    @Override
    public List<Object[]> getListaParaTabla() {
        factory = Persistence.createEntityManagerFactory("R-C_Unicor_LoricaPU");
        EstudianteJpaController controller = new EstudianteJpaController(factory);

        List<Object[]> list = new ArrayList();
        for (Estudiante estudiante : controller.findEstudianteEntities()) {
            list.add(new Object[]{
                estudiante.getIdEstudiante(),
                estudiante.getInformacionBasicaId().getNombres(),
                estudiante.getInformacionBasicaId().getApellidos()
            });
        }
        return list;
    
    }

    @Override
    public String[] getNombreDeColumnas() {
    return new String[]{"ID", "NOMBRES", "APELLIDOS"};    
    }
    
    private void CargarSede() {
        factory = Persistence.createEntityManagerFactory("R-C_Unicor_LoricaPU");
        List<Sede> list = new SedeJpaController(factory).findSedeEntities();
        for (Sede list1 : list) {
            cSedes.addItem(list1);
        }
    }
}