/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RC_Unicor_Lorica_Interfaz_Principal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AndresFelipe
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        TabPrincipal = new javax.swing.JTabbedPane();
        PanelAdministrar = new javax.swing.JPanel();
        BotonRegistrarFacultad = new javax.swing.JButton();
        BotonRegistrarPrograma = new javax.swing.JButton();
        BotonRegistrarMateria = new javax.swing.JButton();
        BotonRegistrarDocente = new javax.swing.JButton();
        BotonRegistrarEstudiante = new javax.swing.JButton();
        BotonRegistrarCurso = new javax.swing.JButton();
        BotonRegistrarUsuarios = new javax.swing.JButton();
        PanelReportes = new javax.swing.JPanel();
        BotonReportesSemanal = new javax.swing.JButton();
        PanelConexion = new javax.swing.JPanel();
        BotonNuevaConexion = new javax.swing.JButton();
        Barra_de_Menu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        BotonRegistrarFacultad.setText("Reg. Facultad");

        BotonRegistrarPrograma.setText("Reg. Programa");

        BotonRegistrarMateria.setText("Reg. Materia");

        BotonRegistrarDocente.setText("Reg. Docente");

        BotonRegistrarEstudiante.setText("Reg. Estudiantes");

        BotonRegistrarCurso.setText("Reg. Cursos");

        BotonRegistrarUsuarios.setText("Reg. Usuarios");

        javax.swing.GroupLayout PanelAdministrarLayout = new javax.swing.GroupLayout(PanelAdministrar);
        PanelAdministrar.setLayout(PanelAdministrarLayout);
        PanelAdministrarLayout.setHorizontalGroup(
            PanelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdministrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegistrarFacultad)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarPrograma)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarMateria)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarDocente)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarEstudiante)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarCurso)
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrarUsuarios)
                .addContainerGap())
        );
        PanelAdministrarLayout.setVerticalGroup(
            PanelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdministrarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistrarFacultad)
                    .addComponent(BotonRegistrarPrograma)
                    .addComponent(BotonRegistrarMateria)
                    .addComponent(BotonRegistrarDocente)
                    .addComponent(BotonRegistrarEstudiante)
                    .addComponent(BotonRegistrarCurso)
                    .addComponent(BotonRegistrarUsuarios))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TabPrincipal.addTab("Administrar Sistema", PanelAdministrar);

        BotonReportesSemanal.setText("Reporte Semanal");
        BotonReportesSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReportesSemanalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelReportesLayout = new javax.swing.GroupLayout(PanelReportes);
        PanelReportes.setLayout(PanelReportesLayout);
        PanelReportesLayout.setHorizontalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonReportesSemanal)
                .addContainerGap(706, Short.MAX_VALUE))
        );
        PanelReportesLayout.setVerticalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonReportesSemanal)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TabPrincipal.addTab("Reportes", PanelReportes);

        BotonNuevaConexion.setText("Nueva Conexion");

        javax.swing.GroupLayout PanelConexionLayout = new javax.swing.GroupLayout(PanelConexion);
        PanelConexion.setLayout(PanelConexionLayout);
        PanelConexionLayout.setHorizontalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonNuevaConexion)
                .addContainerGap(710, Short.MAX_VALUE))
        );
        PanelConexionLayout.setVerticalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotonNuevaConexion)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TabPrincipal.addTab("Conexion", PanelConexion);

        MenuFile.setText("File");
        Barra_de_Menu.add(MenuFile);

        MenuEdit.setText("Edit");
        Barra_de_Menu.add(MenuEdit);

        setJMenuBar(Barra_de_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPrincipal)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReportesSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReportesSemanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonReportesSemanalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_de_Menu;
    private javax.swing.JButton BotonNuevaConexion;
    private javax.swing.JButton BotonRegistrarCurso;
    private javax.swing.JButton BotonRegistrarDocente;
    private javax.swing.JButton BotonRegistrarEstudiante;
    private javax.swing.JButton BotonRegistrarFacultad;
    private javax.swing.JButton BotonRegistrarMateria;
    private javax.swing.JButton BotonRegistrarPrograma;
    private javax.swing.JButton BotonRegistrarUsuarios;
    private javax.swing.JButton BotonReportesSemanal;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JPanel PanelAdministrar;
    private javax.swing.JPanel PanelConexion;
    private javax.swing.JPanel PanelReportes;
    private javax.swing.JTabbedPane TabPrincipal;
    // End of variables declaration//GEN-END:variables
}
